[workspace]
members = ["cargo:."]

[dist]
cargo-dist-version = "0.30.3"
ci = "github"
installers = ["shell", "powershell", "homebrew"]
tap = "sudosubin/homebrew-tap"
install-path = "~/.local/bin"
github-attestations = true
github-attestations-phase = "host"
publish-jobs = ["homebrew", "./publish-crate"]
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "x86_64-unknown-linux-gnu",
  "aarch64-pc-windows-msvc",
  "x86_64-pc-windows-msvc",
]
github-custom-job-permissions = { "publish-crate" = { id-token = "write", contents = "read" } }

[dist.github-custom-runners]
global = "ubuntu-24.04"
aarch64-apple-darwin = "macos-latest"
x86_64-apple-darwin = "macos-15-intel"
aarch64-pc-windows-msvc = "windows-11-arm"
x86_64-pc-windows-msvc = "windows-latest"

[dist.github-custom-runners.aarch64-unknown-linux-gnu]
runner = "ubuntu-24.04-arm"
container = { image = "buildpack-deps:22.04", host = "aarch64-unknown-linux-gnu", package_manager = "apt" }

[dist.github-custom-runners.x86_64-unknown-linux-gnu]
runner = "ubuntu-24.04"
container = { image = "buildpack-deps:22.04", host = "x86_64-unknown-linux-gnu", package_manager = "apt" }
